### PR TITLE
Updated dependency on constellation:console

### PR DESCRIPTION
**Pull request by JackAdams**
Tabbing from within Constellation, breaks the view, so I’ve selfishly
added tabindex=“-1”, but you may not want it on your input fields… :-p

### CODE REVIEW

**Comment by rclai** [comment]
Not a problem, I could care less about the tab index.

**Comment by JackAdams** [comment]
Cheers!

**Comment by rclai** [comment]
Man, you've blown up the DDP inspector download count on Atmosphere haha. Thanks.

**Comment by JackAdams** [comment]
It deserves the attention.  It's cool.  I just used it again to good effect tonight while debugging.  Instead of: writing some `console.log`s, waiting for the hot code reload, clicking on the UI to run the method again, seeing what happened in the server console, deleting the `console.log`s ... I just opened the ddp inspector and had a look at the params that were getting sent down the wire. A couple of minutes saved right there.

**Pull request merged**
