### PR TITLE
Made ddp-inspector pluggable to Constellation

### PR DESCRIPTION
**Pull request by JackAdams**
Constellation is a dev console that looks a lot like Mongol, but is
extensible with custom plugins.  This PR turns ddp-inspector into a
zero-config Constellation plugin if Constellation is present
in the app.  If it's not, ddp-inspector just works as usual as a standalone widget.

Sorry it's such an invasive PR.  I had to make a lot more changes than I wanted to, but I think I've left all existing functionality completely intact and unaltered.

### CODE REVIEW

**Comment by rclai** [comment]
Yay! This is so cool. Thanks for making Constellation. I remember you and I had something like this in mind until, well, Meteor Toys happened ***_cough**_*.

I'll check this out.

I'm still struggling to make DDP Inspector perform better because the DDP messages coming would just totally rape the browser. How did it perform on your end?

**Comment by JackAdams** [comment]
I've only tested it very lightly on a very light app.  I'll give it a try on a big bad app and let you know.

**Comment by JackAdams** [comment]
I just gave it a quick try on a bigger app.  I didn't notice too much (if any) difference in app performance.  Does it create problems if you leave it on for a long time?

**Comment by rclai** [comment]
I haven't made it stop saving documents to `DDPMessages` when you don't have the panel open, so as the collection fills up, things might get slow? In which case you might need to hit the Reset button to clear it up.

**Comment by JackAdams** [comment]
I reckon this is a small price to pay for having ddp messages right there in the browser.  It's very revealing -- already helped me debug Constellation a bit when I noticed some unexpected parameters in messages.

**Comment by rclai** [comment]
Cool, I'm glad you found it helpful. I still haven't checked this out yet, but what I'll probably do is merge it and later clean it up because right now it's a colossal mess.

**Comment by JackAdams** [comment]
That'd be awesome.

**Comment by rclai** [comment]
Holy cows, I just checked it out, it looks beautiful!

**Comment by JackAdams** [comment]
Haha... glad you like it.  Hold off merging that PR for a bit.  I've got a new minor release of the console coming out later today and I'll update the dependencies.

**Comment by rclai** [comment]
Okay.

**Comment by JackAdams** [comment]
All right.  I think this is ready to go.

**Comment by JackAdams** [comment]
Sorry about all the commits that just alter the dependency on `contellation:console`.  I wish there was a way we could just do:

```
api.use('constellation:console@latest')
```

**Comment by JackAdams** [comment]
Hey, I had an idea.

First, full disclosure: I've put some little arrows on each message to indicate whether the message is going in or out.  This is the only change that makes the previous version of ddp-inspector distinguishable from the version in this PR.

Wondering about this... what about making it so if you click on an "outgoing" arrow it sends the same DDP message again.  Good for debugging server-side methods and publications.  I'd be happy to code it up if you think it's worthwhille.

**Comment by rclai** [comment]
That would be cool!

First let me merge this in and then you can submit that as a separate PR.

**Comment by rclai** [comment]
For some reason I can't see those arrows you're talking about. Could it be a browser issue? I'm using latest Chrome.

By the way I had to do the `Meteor.defer` on here to make DDP inspector work right alongside React, so it seems to be related.

**Comment by rclai** [comment]
I noticed I could see the right arrow, but not the left arrow, it just shows as a square.

**Comment by JackAdams** [comment]
Okay. I'll fix the arrows up soon. They're some weird UTF-8 characters, but I'll just replace them with `=>` and `<=`, which should work for everyone. (They show in the latest Chrome for me, but don't seem to be matching in style -- the left arrow is thicker than the right arrow. Odd.)

**Comment by JackAdams** [comment]
The `<=` type arrows were just too ugly, so I've changed the UTF-8 characters to less obscure ones instead. They're working in latest Chrome and FF on my mac -- although they're still mismatched in appearance in Chrome.

Well ... I think this is it for commits for this pull request.  I've just released a new minor version of Constellation (1.2.0) and hope that will be it for a while.  I've (manually) tested `lai:ddp-inspector` in a development app in both the Constellation context and the standalone mode and everything seems to be working.

**Comment by JackAdams** [comment]
Hi Richard,
Any plans to merge this in the near future?  I want to release a distro for Constellation (all my favourite plugins in one package), but waiting on `ddp-inspector`, as it's pretty darn useful! :-)

**Comment by rclai** [comment]
AHh, yeah, I'm gonna try and get it out tonight.

**Comment by JackAdams** [comment]
Cool. Looking forward to it!

**Comment by rclai** [comment]
Alright, there it is!

**Comment by JackAdams** [comment]
Awesome. Thanks man. Included it in a bunch of projects already.

**Pull request merged**
